### ISSUE TITLE
Linking on Apple Sillicon

### ISSUE THREAD

**Issue by mdblabs** [thejinchao/turbolink-libraries#3]
Hi!
First of all congratulations for the project! I spent a few days looking for UE + gRPC integration till I find your library.

I've recompiled the whole project from scratch without any issue, just following documented steps. I needed to rebuilt it as there is no binaries for Apple M1 Arch (arm64).

Once compiled, I tested on my UE5.3 test bench, but i'm getting linking issues, for basically every symbol:

`Undefined symbols for architecture arm64`

Any idea? 

**Context:**

- Apple M1
- UE5.3
- XCode 15.0
- MacOS Ventura 13.6

Thank you very much!

**Comment by thejinchao** [comment]
I just happened to merge the branch compatible with UE 5.3 into the trunk. You can try the current main branch. When I compiled the mac version, I used the `Universal` method, which should combine the two architectures of `x86_64` and `arm64`, so it should be able to be used directly. But I do not have an Apple M1 environment, so I didn't test it.
Good luck.

**Comment by mdblabs** [comment]
Thank you so much! Now is working.
